# Generated by Django 5.0 on 2024-03-20 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lemmas', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LogsLemmas',
        ),
    ]
